apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-secrets
  namespace: conjur-demo-app
data:
  secrets.yml: |- # Enter the paths of the secrets mentioned as pre-requisite
    PASSWORD_1: !var vault/LOB-Sync-Lab/Test/test/password
    PASSWORD_2: !var vault/LOB-Sync-Lab/Test/test2/password
    PASSWORD_3: !var vault/LOB-Sync-Lab/Test/test3/password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: conjur-demo-app # Namespace should match with the Conjur Project (step before)
  labels:
    app: demo-app
spec:
  replicas: 1
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
    spec:
      containers:
        - name: authenticator
          image: cyk/conjur-authn-k8s-client:0.26.1 # This image can be found on the CyberArk Marketplace
          env:
            - name: CONJUR_TOKEN_TIMEOUT
              value: "1m0s"
            - name: CONTAINER_MODE
              value: sidecar
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CONJUR_AUTHN_URL
              value: "https://conjur-follower.conjur-follower.svc.cluster.local/authn-k8s/follower-oc416" # AUTHN_URL made of https://<Service-name>.<namespace-name>.<object>.<cluster-domain>/*
            - name: CONJUR_ACCOUNT
              value: conjur-test
            - name: CONJUR_AUTHN_LOGIN
              value: "host/environments/kubernetes/dev/projects/demo-app/conjur-demo-app" # AUTH_HOST (must start with "host/")
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  key: conjur_public_ca.crt # ConfigMap Key, where the certificate is located
                  name: conjur-cert         # ConfigMap Name mentioned on the step above
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
        - name: demo-app
          image: cyk/conjur-probe-app:latest # This image can be found on the CyberArk Marketplace
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "/scripts/runAll.sh; tail -f /dev/null;" ]
          imagePullPolicy: Always
          env:
            - name: CONJUR_APPLIANCE_URL
              value: "https://conjur-follower.conjur-follower.svc.cluster.local" # Should be the FQDN of the AUTHN_URL of line 48
            - name: CONJUR_ACCOUNT
              value: conjur-test
            - name: CONJUR_AUTHN_TOKEN_FILE
              value: /run/conjur/access-token
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  key: conjur_public_ca.crt
                  name: conjur-cert
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
              readOnly: true
            - mountPath: /test
              name: conjur-app-secrets
              readOnly: true
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: conjur-app-secrets
          configMap:
            name: demo-app-secrets
            optional: false
      restartPolicy: Always
  selector:
    matchLabels:
      app: demo-app